### ISSUE TITLE
Support for large emails via smart disk buffering?

### ISSUE THREAD

**Issue by Xeoncross** [mhale/smtpd#12]
I want to support accepting large SMTP `DATA` bodies without having to store the body in memory. Using a [disk buffer](https://github.com/mailgun/multibuf) or "[memory-constrained buffer](https://github.com/cardamaro/mem_constrained_buffer)" would allow the server to accept larger bodies from multiple clients concurrently.

https://github.com/mhale/smtpd/blob/master/smtpd.go#L603

```go
// Buffer up to ~6MB in RAM and limit max buffer size to ~200MB
multibuf.New(r, multibuf.MemBytes(1024 * 1024 * 6), multibuf.MaxBytes(1024 * 1024 * 200))
```

**Comment by mhale** [comment]
Great idea. I'll have a go at implementing it over the holiday period.

**Comment by Xeoncross** [comment]
I had time today and went ahead and added [streaming multipart/mime body support as a test](https://github.com/Xeoncross/smtpd/blob/master/session.go#L177) everything seems to be working. I still have more to do but wanted to update here in case you want to borrow any ideas. 

Unfortunately, this can't be integrated back as a PR because I removed all the authentication code/tests which made up about half of the codebase. I am looking to run a public server and have no use for AUTH requests.

**Comment by mhale** [comment]
I am interested in this streaming attachment idea. Thanks for following up.

Btw, AUTH commands return 502 not implemented if no AuthHandler is defined. They'd be rejected in the default configuration.

**Comment by dubcanada** [comment]
@Xeoncross - I am interested in this as well I noticed @mhale has not done this yet.

Do you have intentions of maintaining the fork or should we work towards integrating your work with this repo?

**Comment by Xeoncross** [comment]
@dubcanada I'm not currently using my fork, so I don't have any plans to maintain it. Work on integrating it into this project would be great. That said, it's also mostly complete as-is in my fork, so it should be immediately usable.

I would checkout https://github.com/emersion?tab=repositories repositiories as well. I've forked, tested and compared dozens of Go libraries in the "email" space and there is no one that compares to the work he's done. He's forked the official SMTP library and written DKIM, MIME, WebDAV, SMTP and many other libraries. So check his work out for more information.

Even with my fork of this project adding streaming and proper use of textproto I was still [unable to beat his more feature-complete version](https://github.com/emersion/go-smtp/issues/46).

**Comment by mhale** [comment]
Closing due to age.
