### ISSUE TITLE
sending Email

### ISSUE THREAD

**Issue by khaledelbasha22** [mhale/smtpd#13]
how i can use it for send email for other server like @gmail.com

**Comment by mhale** [comment]
If you mean you want to use this library to send an email from Go code, that's not what it does - it receives emails. It does not send them. If you just want to send emails, have a read of the Go [SendMail function](https://golang.org/pkg/net/smtp/#SendMail) documentation.

If you want to use this library to create your own mail forwarder program, have a look at my [Mailrouter project](https://github.com/mhale/mailrouter) for an example of how to do it.
