### ISSUE TITLE
Wrong operator used?

### ISSUE THREAD

**Issue by tegk** [mhale/smtpd#21]
What happens if the length is bigger than 100?
Should this not be >= 100?
https://github.com/mhale/smtpd/blob/d7a07f75233677fad3c2eb73754b7033ed08760a/smtpd.go#L326

**Comment by Ruxton** [comment]
It's a loop parsing line by line, it runniung for every line sent to the server. So therefore every instance of RCPT being sent. If `== 100` then it'll stop allowing you to add new ones. It should never get above 100.
