### ISSUE TITLE
how to send email?

### ISSUE THREAD

**Issue by li-xunhuan** [mhale/smtpd#32]

**Comment by wraix** [comment]
You connect with an SMTP client and follow the protocol. I use Mutt.

**Comment by adrian-badulescu** [comment]
Actually this is a good question as the documentation lacks clarity, meaning the handler could be more explicit, in this form is unusable 
`` 
func rcptHandler(remoteAddr net.Addr, from string, to string) bool {
    domain = getDomain(to)
    return domain == "mail.example.com"
}
``

**Comment by Fedasov** [comment]
Hello, I also faced such a problem. I can't send the message. Writes panic: unencrypted connection. Although our mail service is based on https. Please tell me where I made a mistake?

**Comment by mhale** [comment]
This library is for receiving email, not sending email. For sending email, you might have more success with [net/smtp](https://pkg.go.dev/net/smtp).
