### ISSUE TITLE
Possibility to publish a version

### ISSUE THREAD

**Issue by zaclimon** [mhale/smtpd#33]
Nice job for the implementation! I was wondering, how about this implementation could be versioned and published so it could be used as a library? I'm using the GitHub link right now for importing, but the version is 0.0.0 and could be prone to new changes if any.

The version I retrieve from my `go.mod` file with the unclear versioning is:  `v0.0.0-20210322105601-438c8edb069c`.

**Comment by mhale** [comment]
I've just pushed a v0.8.0 tag, would you please verify that it works?

**Comment by zaclimon** [comment]
I can confirm it works, thank you for looking at this!
