### ISSUE TITLE
how to get the body of the email?

### ISSUE THREAD

**Issue by hiqsociety** [mhale/smtpd#34]
great work! i've managed to get everything set up but dunno how to get the body of the msg. I know how to get the subject but how do i get the body?
```
    msg, _ := mail.ReadMessage(bytes.NewReader(data))
    subject := msg.Header.Get("Subject")
    log.Printf("Received mail from %s for %s with subject %s", from, to[0], subject)
    return nil
```

**Comment by mhale** [comment]
You probably want something like:

```go
	body, err := io.ReadAll(msg.Body)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("%s", body)
```

There is a [full example](https://pkg.go.dev/net/mail@go1.19.2#ReadMessage) in the mail package docs.

**Comment by hiqsociety** [comment]
just figured out. thx!
