### ISSUE TITLE
Return Message ID in SMTP response after message

### ISSUE THREAD

**Issue by Sn0wCrack** [mhale/smtpd#38]
Currently after the DATA command is issued the response always returns as `250 2.0.0 Ok: queued`, some systems rely on receiving the SMTP Message ID in the SMTP response for logging purposes.

It would be good if either a custom function could be passed in for generating the SMTP Message ID, or if the Handle function could return a Message ID that will be used in the response.

Ideally the response would be formatted as `250 2.0.0 Ok: queued as <message-id>`

**Comment by mhale** [comment]
A bit of research indicates a wide variety of message ID formats. Do you have a preference?

**Comment by Sn0wCrack** [comment]
I think it would be ideal if the Message ID could be returned from one of the handler functions, or a new handler function would be able to be used to pass those details through.

Generally speaking the applications using this library would be the ones managing the Message ID for other purposes (logging, queuing, etc.)

**Comment by mhale** [comment]
I've added a new handler function type called MsgIDHandler in a branch named "return-message-id". It should behave the same as the regular Handler and print whatever ID is returned, however I haven't written any test coverage yet. Would you mind testing it to see if it fits your needs?

**Comment by Sn0wCrack** [comment]
Oh wow thank you for that, it's really appreciated, I've had a quick look and this seems pretty perfect for what I'd need.

My main aim was to integrate this into [Mailpit](https://github.com/axllent/mailpit) as this was one of the features missing from the project that Mailhog had and it caused some issues with a few applications we have when locally testing them.

I'll try and have a play around with the branch and integrating it into Mailpit sometime this week, thanks again!

**Comment by Sn0wCrack** [comment]
@mhale 

I've tested this out and it seems to work great from my testing, very easy to just change the existing function to work with this.

Thanks again!

**Comment by Sn0wCrack** [comment]
Was there any chance of this getting merged into master at any point @mhale?

My testing from a while ago with it and merging it into Mailpit seemed to work great.

**Comment by mhale** [comment]
It's in master now, hopefully it still works.

**Comment by Sn0wCrack** [comment]
Awesome! Thank you very much!
