### ISSUE TITLE
Ability to set maximum recipients

### ISSUE THREAD

**Issue by axllent** [mhale/smtpd#39]
Hi there. 

Currently there is a maximum of 100 recipients hardcoded. Whilst I understand that this should be a default, the RFC states that an SMTP server must handle a minimum of 100 recipients, not the maximum. I use your awesome package in [Mailpit](https://github.com/axllent/mailpit) (email / SMTP testing tool) and it would be extremely helpful if your module could allow a custom max to be set.

Thank you.

**Comment by mhale** [comment]
Hi, I've added a MaxRecipients field to the Server structure. Does that suit your needs?

**Comment by axllent** [comment]
That is awesome @mhale, thank you. I've tested with the master branch and can confirm this works exactly as expected :+1:  Would you mind please tagging a new version with this so I can implement it downstream (so I can revert to tagged releases)?

Thanks again!

**Comment by mhale** [comment]
I've pushed a tag named v0.8.1.

**Comment by axllent** [comment]
That is fantastic, thanks so much @mhale - exactly what I needed! :rocket: Works like a charm...
