### ISSUE TITLE
tls support

### ISSUE THREAD

**Issue by ginkoob** [mhale/smtpd#5]
is there tls support planned or can you provide guidance how to implement it?

**Comment by mhale** [comment]
I have no plans to support TLS at the moment. Using it with SMTP is less straightforward than with HTTP and as I don't need encryption or authentication for my use case, I thought it best to keep the code as simple as possible.

If you want to implement it yourself, these links may be helpful:

- [SSL vs TLS vs STARTTLS](https://www.fastmail.com/help/technical/ssltlsstarttls.html)
- [Opportunistic TLS](https://en.wikipedia.org/wiki/Opportunistic_TLS)
- [RFC 2487: SMTP Service Extension for Secure SMTP over TLS](https://tools.ietf.org/html/rfc2487)
- [func (*Client) StartTLS](https://golang.org/pkg/net/smtp/#Client.StartTLS)

**Comment by mhale** [comment]
I've just added TLS support. Please have a play with it and let me know how you find it.

**Comment by mhale** [comment]
Closing this issue as it's been three months without any response.
