### ISSUE TITLE
Feature request: Connection Timeout

### ISSUE THREAD

**Issue by egeland** [mhale/smtpd#6]
It seems like if a client connects, it can stay connected forever - would be good to have a timeout on idle connections. 😅

**Comment by mhale** [comment]
You're correct, and I like the idea. Thanks. I'll have a look into it.

**Comment by Ruxton** [comment]
Wouldn't be that difficult to implement in the serve loop ;)

**Comment by businessworks** [comment]
@Ruxton A connection level timeout would be easy - SetDeadline() will take care of that. However, RFC 2821 specifies different timeouts per command, and I like to be RFC compliant, so I want to have a look at how feasible that might be before I commit anything.

**Comment by mhale** [comment]
@Ruxton A connection level timeout would be easy - SetDeadline() will take care of that. However, RFC 2821 specifies different timeouts per command, and I like to be RFC compliant, so I want to have a look at how feasible that might be before I commit anything.

**Comment by mhale** [comment]
@egeland RFC 5321 specifies a minimum server timeout of 5 minutes while waiting for a command, so I will make that the default. Would you prefer it to send a message before disconnecting (and if so, what message?) or just silently close the connection?

**Comment by egeland** [comment]
I'm not sure what the usual behaviour of SMTP servers are, when closing due
to timeout.
Might be worth looking at the documentation for postfix or exim..?

**Comment by mhale** [comment]
Postfix sends "421 4.4.2 macbookpro.home Error: timeout exceeded" on connection, HELO and DATA timeouts, so I'll follow that example.

**Comment by mhale** [comment]
I've implemented a connection timeout and there haven't been any complaints so I'm closing this issue.
